# Generated by Django 3.2.7 on 2021-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='master',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
